### ISSUE TITLE
Ambiguity with RotMatrix 

### ISSUE THREAD

**Issue by Paethon** [Evizero/Augmentor.jl#15]
Hi

I suddenly become the following error when using Augmentor

```
MethodError: Rotations.RotMatrix{2,Float64,4}(::StaticArrays.SArray{Tuple{2,2},Float64,2,4}) is ambiguous. Candidates:
  (::Type{Rotations.RotMatrix{N,T,L}})(x::AbstractArray) where {N, T, L} in Rotations at /home/paethon/.julia/v0.6/Rotations/src/core_types.jl:78
  (::Type{SA})(a::StaticArrays.StaticArray) where SA<:StaticArrays.StaticArray in StaticArrays at /home/paethon/.julia/v0.6/StaticArrays/src/convert.jl:4
Possible fix, define
  (::Type{Rotations.RotMatrix{N,T,L}})(::StaticArrays.StaticArray)
```

Reason is `rotations.jl` line 324

```julia
recenter(RotMatrix(deg2rad(Float64(safe_rand(op.degree)))), center(img))
```

Unfortunately I am not yet confident enough to fix this myself

**Comment by Evizero** [comment]
This is likely related to https://github.com/JuliaImages/ImageTransformations.jl/issues/43

Will look into it

**Comment by Paethon** [comment]
Ahh, did not see this :) Thanks for the fast reply!

**Comment by Evizero** [comment]
The issue seems to be in upstream (StaticArrays).

If this is interfering with your work, try 

```julia
Pkg.pin("StaticArrays", v"0.6.4")
```

until this issue is closed

**Comment by Evizero** [comment]
Also I just noticed another upstream issue that caused an error. you may want to check out `master` of Augmentor.jl for now. I pushed a quickfix for that

**Comment by Paethon** [comment]
That solved it. Thanks for the quick response! And greetings from another Austrian (did not expect that :) )

**Comment by Evizero** [comment]
Once https://github.com/JuliaLang/METADATA.jl/pull/12089 is merged you can free your pinned packages again to their tagged versions.

```julia
Pkg.free("StaticArrays")
Pkg.free("Augmentor")
```

All the issues should be resolved with the merge and tag of https://github.com/FugroRoames/Rotations.jl/pull/50

**Comment by Paethon** [comment]
Much appreciated! Thank you!
