### ISSUE TITLE
`ConvertEltype(Gray)` not working as expect anymore

### ISSUE THREAD

**Issue by Evizero** [Evizero/Augmentor.jl#17]
It seems that for some reason or another, leaving the inner type open for `Gray` now causes fatal issues with inference. Will either have to force user to be specific with `ConvertEltype(Gray{INNER})` or see if I can fix this.

**Comment by Evizero** [comment]
Seems to only be an issue if followed by a SplitChannel(). I suspect the issue is somewhere upstream with `channelview`

**Comment by johnnychen94** [comment]
https://github.com/Evizero/Augmentor.jl/blob/6055db7493352257ddc7b97d63ecaf8ccb43faea/src/operations/convert.jl#L54-L60

A simple decision could be: if storage type `T` here is `Any`, then use `eltype(eltype(img))` as the output type. Of course we need to deal with cases for color types that don't support `N0f8` or `Bool` (e.g., `Lab`)

Update:

This would cause type-instability so it doesn't work.

**Comment by johnnychen94** [comment]
> causes fatal issues with inference

I guess it's no longer an issue now. @Evizero does this look good to you?

```julia
julia> @inferred(augment(img, ConvertEltype(Gray))) |> summary # Gray{Any}
"300×400 Array{Gray{Any},2} with eltype Gray"

julia> pl = SplitChannels() |> ConvertEltype(Gray)
2-step Augmentor.ImmutablePipeline:
 1.) Split colorant into its color channels
 2.) Convert eltype to Gray{Any}

julia> @inferred(augment(img, pl)) |> summary # Gray{N0f8}
"4×300×400 Array{Gray{N0f8},3} with eltype Gray{Normed{UInt8,8}}"
```

**Comment by timholy** [comment]
Just a brief comment, instead of `mappedarray(c->convert(T,c), img)` it's slightly better to use `of_eltype(T, img)` because it also defines the inverse operation and thus supports `setindex!`. https://github.com/JuliaArrays/MappedArrays.jl#of_eltype

**Comment by barucden** [comment]
I confirm that the issue is gone. See #95, which implements a few test cases for this.
