### ISSUE TITLE
`Either` may not work properly with `Pipeline`

### ISSUE THREAD

**Issue by johnnychen94** [Evizero/Augmentor.jl#36]
For the following three seeming "equivalent" operations, the first one randomly changes the image size...

For `img = testimage("cameraman")`:

* `augment(img, Either(Rotate90()) |> FlipY())` returns image of size `(512, 512)` **or** `(513, 512)`
* `augment(img, Rotate90() |> FlipY())` returns image of size `(512, 512)`
* `augment(augment(img, Either(Rotate90())), FlipY())` returns image of size `(512, 512)`

**Comment by johnnychen94** [comment]
Without any evidence, this issue might be related to the unrolling part of lazy operations in `augment_impl`.

A workaround is to insert a `CacheImage` operation after `Either` to "enforce eager mode", e.g., `augment(img, Either(Rotate90()) |> CacheImage() |> FlipY())`

**Comment by Evizero** [comment]
yea. Rotate90 and NoOp only share the affine option for lazy. and there is likely some rounding error when rotating

**Comment by barucden** [comment]
I could not reproduce on the current master. Is it possible that it has been fixed?

```julia
julia> using Augmentor, TestImages

julia> img = TestImages.testimage("cameraman");

julia> a(img) = augment(img, Either(Rotate90()) |> FlipY())
a (generic function with 1 method)

julia> b(img) = augment(img, Rotate90() |> FlipY())
b (generic function with 1 method)

julia> c(img) = augment(augment(img, Either(Rotate90())), FlipY())
c (generic function with 1 method)

julia> unique!([size(a(img)) for i in 1:1000])
1-element Vector{Tuple{Int64, Int64}}:
 (512, 512)

julia> unique!([size(b(img)) for i in 1:1000])
1-element Vector{Tuple{Int64, Int64}}:
 (512, 512)

julia> unique!([size(c(img)) for i in 1:1000])
1-element Vector{Tuple{Int64, Int64}}:
 (512, 512)

```

**Comment by johnnychen94** [comment]
Great! I didn't notice this was fixed but it might be related to the discretization trick in ImageTransformations: https://github.com/JuliaImages/ImageTransformations.jl/pull/107 and https://github.com/JuliaImages/ImageTransformations.jl/pull/114 This might only happen when the affine method is called. Another similar issue is https://github.com/Evizero/Augmentor.jl/issues/77

An upcoming change in ImageTransformations@v0.9 is https://github.com/JuliaImages/ImageTransformations.jl/pull/143
