### ISSUE TITLE
random failure OffsetArray tests for Scale and Zoom

### ISSUE THREAD

**Issue by johnnychen94** [Evizero/Augmentor.jl#38]
This bug is identified during the upgrade of Augmentor #31 Since that PR is growing bigger and becoming hard to review, it's better to open an issue here and fix it separately.

```julia
julia> using Augmentor, ImageCore, OffsetArrays, ImageDistances

julia> img = rand(Gray{N0f8}, 64, 64);

julia> out1 = Augmentor.applyeager(Scale(1.5), img);

julia> out2 = Augmentor.applyeager(Scale(1.5), OffsetArray(img, -1, -1));

julia> out1 == out2
false

julia> euclidean(out1, out2)
0.044884406f0
```

This bug might be related to upstream packages: Interpolation and ImageTransformation.jl

Update: downscale (e.g., `Scale(0.2)` ) is not affected.

**Comment by johnnychen94** [comment]
This issue might not be so easy to fix, as far as I can identify at present, the accuracy issue is due to different center generated by `toaffinemap`. (This might not be the root reason, but I'll just post it here as log to myself)

```julia
julia> using Augmentor: toaffinemap

julia> op = Scale(1.5);

julia> img = rand(Gray{N0f8}, 64, 64);

julia> img2 = OffsetArray(img, -1, -1);

julia> toaffinemap(op, img, (1.5, 1.5))
AffineMap([1.5 0.0; 0.0 1.5], [-16.25, -16.25])

julia> toaffinemap(op, img2, (1.5, 1.5))
AffineMap([1.5 0.0; 0.0 1.5], [-15.75, -15.75])
```

**Comment by Evizero** [comment]
well but numerical inaccuracy should be expected though, right? The basic idea was to always apply the affine operation around the origin, if I remember correctly.

**Comment by johnnychen94** [comment]
I guess so, but since I'm not the Augmentor expert :P, I wish I could make the test pass without relaxing them.

I'm actually thinking of a workaround to this inaccuracy, that striping the offsets, applying affine operation, and adding back offsets. But that would be tricky and there might be a performance issue as well.

**Comment by johnnychen94** [comment]
#43 does not fix this issue; it only relaxes the accuracy requirement for those identified failed test cases. Hence I'll still keep this issue open.

**Comment by johnnychen94** [comment]
Well, since general machine learning tasks don't really need such accuracy, I'll just close this issue...
