### ISSUE TITLE
Rotation without changing size 

### ISSUE THREAD

**Issue by ereday** [Evizero/Augmentor.jl#5]
Hi, I want to rotate the image using Augmentor.jl to do that, I took an sample image from the [net](http://www.rd.com/wp-content/uploads/sites/2/2016/04/01-cat-wants-to-tell-you-laptop.jpg). and applied following commands:
```
julia> using Augmentor
julia> using Images  # I use it to load jpg file, if it is possible with Augmentor I can use it too
julia> img = load("test-input.jpg")
julia> size(img)
(1600,2400)
julia> pl = Rotate(45)
julia> img_new = augment(img,pl)
julia> size(img_new)
(2830,2830)

```

Below, I put both the original image (img) and rotated one (img_new). I have two problems here. First of all, when I rotate it, the size of the images changes. Is it possible to keep it constant ? Secondly, why the image brokes at some points like under the keyboard?  If possible I also want to resize the image before rotating it. How could it be integrated in this flow ? 

Original Image:
![test-input](https://user-images.githubusercontent.com/13196191/26899538-1ae5ee68-4bd8-11e7-98a5-6b465df11b8e.jpg)

Rotated Image:
![test-input2](https://user-images.githubusercontent.com/13196191/26899569-2bcf15d8-4bd8-11e7-9d1b-881600891e29.jpg)

**Comment by Evizero** [comment]
Hi! The reason why the image expands is that all original pixel are accessible if need be. Augmentor works by chaining operations to achieve the desired effects.

for example try

```julia
pl = Rotate(45) |> CropSize(size(img))
``` 

To your second question. New pixel that are outside the domain of the original image are set to the nearest neighbour instead to a hard black. This is more common in machine learning.

You can overwrite this explicitly by passing a extrapolation to `augment` that behaves how you want it to behave (see https://github.com/JuliaMath/Interpolations.jl). Here an example where new pixel are simply set to black.

```julia
etp = extrapolate(interpolate(img, BSpline(Linear()), OnGrid()), RGB{N0f8}(0,0,0))
img_new = augment(etp,pl)
```
