### ISSUE TITLE
add documentation settings

### ISSUE THREAD

**Issue by johnnychen94** [Evizero/Augmentor.jl#51]
The last thing to do before registering v0.6.0 in the General registry is to update the documentation.

@Evizero Looks like this repository haven't set up auto-deployment CI for documentation, right? Can you add a deploy key and a secret key (with name `DOCUMENTER_KEY`) following the instruction of https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#travis-ssh-1 I plan to set the documentation via Github action

**Comment by Evizero** [comment]
If the docs are still the way I did them then they don't really work in a CI environment

**Comment by johnnychen94** [comment]
I'm modifying the docs to adapt the current Documenter system; the idea is to rewrite them using DemoCards.jl, which is CI friendly :P

**Comment by johnnychen94** [comment]
Hmmm.. May I tag v0.6.0 in spite of the not updated documents? I need this package registered/tagged for reproduction consideration.

**Comment by Evizero** [comment]
sure
