### ISSUE TITLE
unnecessary type promotion

### ISSUE THREAD

**Issue by AlfTetzlaff** [Evizero/Augmentor.jl#62]
Hi, playing around with the package I just saw that it is often not type stable, e.g. putting in an image containing Float32 it returns a Float64 image. Affected functions I have tested:

Resize
Rotate
Shear
Zoom

I think working on this issue would increase the performance even more.

Edit: Example:
```julia
raw = rand(Float32,8,100,100)
img = view(reinterpret(SVector{8,Float32}, raw), 1,:,:)  # now its an AbstractMatrix
imgcp = copy(img)  # for demo purposes
pl = Rotate(123)
aug = augment(imgcp, pl)
typeof(aug) == typeof(imgcp)
```

**Comment by maxfreu** [comment]
This issue is probably upstream and related to [#359](https://github.com/JuliaMath/Interpolations.jl/issues/359) in Interpolations.jl.

**Comment by AlfTetzlaff** [comment]
Closing, as the fix in Interpolations.jl has been merged.
