### ISSUE TITLE
configure ssh key for tagbot

### ISSUE THREAD

**Issue by johnnychen94** [Evizero/Augmentor.jl#72]
Here's the motivation: 

One GitHub action could not trigger another GitHub action if only configured with `token: ${{ secrets.GITHUB_TOKEN }}`. This limitation means release/tag created by tagbot could trigger the docs CI.

@Evizero could you help set up an ssh key and corresponding github secrets for this? It should be ssh key with write permission in https://github.com/Evizero/Augmentor.jl/settings/keys (public, write permission) and secrets in https://github.com/Evizero/Augmentor.jl/settings/secrets/new (private)

The quick command to generate ssh key:

```
ssh-keygen -t rsa -b 4096 -C "stocker.christof@gmail.com" -f tagbot
```

then copy `tagbot.pub` as keys and `tagbot` as secrets (let's say with name "TagBot").

References:

- https://juliadocs.github.io/Documenter.jl/dev/man/hosting/#GitHub-Actions

**Comment by Evizero** [comment]
Ops. I missed or forgot this. Is this still relevant?

**Comment by johnnychen94** [comment]
Yes, I can update the CI configuration when this is added.

**Comment by Evizero** [comment]
Done. Let me know if i screwed it up :-)

**Comment by johnnychen94** [comment]
hard to tell unless there's a new release; I'll reopen if it doesn't work

**Comment by Evizero** [comment]
I just checked and I did this already. though the name is `TagBot` and not `TAG_BOT` like you mentioned in the mail. Will this work, or would you like me to change the name?

**Comment by Evizero** [comment]
actually the secret is `TAGBOT`

**Comment by Evizero** [comment]
actually hold that though, I think I might have screwed up the last part. I'll redo it now

**Comment by johnnychen94** [comment]
The one I configured in the CI is `TAGBOT`

https://github.com/Evizero/Augmentor.jl/blob/121b70d34881ac1ae3da08ba0e65a644a5d7319e/.github/workflows/TagBot.yml#L12

**Comment by Evizero** [comment]
try now. let me know if it doesnt work

**Comment by johnnychen94** [comment]
Oh, wait. I might not describe the need clearly in my previous mail. I was asking for adding a `TAGBOT` ssh key in UnicodePlots, too.

**Comment by Evizero** [comment]
done as well!
