### ISSUE TITLE
CI fails

### ISSUE THREAD

**Issue by matsueushi** [Evizero/Augmentor.jl#77]
Hello,

Currently CI is falling, it seems it was caused by the ImageTransformations v0.8.8 release. All tests have passed when I downgraded it to v0.8.7. I guess the commit https://github.com/JuliaImages/ImageTransformations.jl/commit/a4f219020ad142c5a5bcdb03486e092fd8d9e02b has changed the result of `invwarpedview`.

```julia
julia> square = [0.1 0.2 0.3; 0.4 0.5 0.6; 0.7 0.6 0.9]
julia> x = Augmentor.prepareaffine(square)
julia> m = Augmentor.toaffinemap(Rotate90(), square)
```
With ImageTransformations v0.8.7:
```julia
julia> Augmentor.invwarpedview(x, m)
3×3 InvWarpedView(extrapolate(interpolate(::Array{Float64,2}, BSpline(Interpolations.Linear())), Flat()), AffineMap([6.123233995736766e-17 -1.0; 1.0 6.123233995736766e-17], [4.0, 0.0])) with eltype Float64 with indices 1:3×1:3:
0.3 0.6 0.9
0.2 0.5 0.6
0.1 0.4 0.7
```
With ImageTransformations v0.8.8:
```julia
julia> Augmentor.invwarpedview(x, m)
4×4 InvWarpedView(extrapolate(interpolate(::Array{Float64,2}, BSpline(Interpolations.Linear())), Flat()), AffineMap([6.123233995736766e-17 -1.0; 1.0 6.123233995736766e-17], [4.0, 0.0])) with eltype Float64 with indices 1:4×1:4:
 0.3  0.6  0.9  0.9
 0.2  0.5  0.6  0.6
 0.1  0.4  0.7  0.7
 0.1  0.4  0.7  0.7
```

**Comment by johnnychen94** [comment]
Yeah, the result looks really wrong here. I'm not sure if I have the time to investigate this, would you help figure out what should be fixed here?

**Comment by matsueushi** [comment]
Okay, I'll take a look.

**Comment by matsueushi** [comment]
I made a PR related to this issue on ImageTransformations.jl
