### ISSUE TITLE
Clean up `gh-pages` branch

### ISSUE THREAD

**Issue by barucden** [Evizero/Augmentor.jl#91]
I noticed that the URL [https://evizero.github.io/Augmentor.jl/](https://evizero.github.io/Augmentor.jl/), which is in the *About* section of the repository takes users to an obsolete documentation. The correct URL is either [https://evizero.github.io/Augmentor.jl/stable/](https://evizero.github.io/Augmentor.jl/stable/) or [https://evizero.github.io/Augmentor.jl/dev/](https://evizero.github.io/Augmentor.jl/dev/).

I investigated further and noticed that the `gh-pages` branch contains even more obsolete content. I listed the author dates for each top-level file/directory using `git ls-tree --name-only HEAD | while read filename; do   echo "$(git log -1 --format="%ad" -- $filename) $filename"; done`:
```
Sun Feb 4 20:34:49 2018 +0100 LICENSE
Mon Jul 9 09:22:54 2018 +0200 assets
Sun Feb 4 20:34:49 2018 +0100 background
Sun Aug 8 06:48:07 2021 +0000 dev
Mon Jul 9 09:33:08 2018 +0200 generated
Sun Feb 4 20:34:49 2018 +0100 gettingstarted
Sun Feb 4 20:34:49 2018 +0100 images
Sun Apr 8 21:05:15 2018 +0200 index.html
Sun Apr 8 21:05:15 2018 +0200 indices
Mon Jul 9 09:22:54 2018 +0200 interface
Mon Jul 9 09:22:54 2018 +0200 operations
Sun Feb 4 20:34:49 2018 +0100 search
Mon Jul 9 09:22:54 2018 +0200 search_index.js
Sun Aug 8 02:16:43 2021 +0000 stable
Sun Aug 8 02:16:43 2021 +0000 v0.6
Fri Sep 18 11:59:14 2020 +0000 v0.6.2
Mon May 17 13:17:17 2021 +0000 v0.6.3
Mon Jul 12 20:12:00 2021 +0000 v0.6.4
Sun Aug 8 02:16:43 2021 +0000 v0.6.5
Fri Sep 18 11:57:43 2020 +0000 versions.js
```

These items have not been updated in 2021:
```
LICENSE
assets
background
generated
gettingstarted
images
index.html         # keep this one
indices
interface
operations
search
search_index.js
v0.6.2             # keep this one
versions.js        # keep this one
```

I believe they (with the three exceptions) are not needed anymore, and we are free to dispose them.

I propose:

1. Change the top-level `index.html` so that it redirects to [https://evizero.github.io/Augmentor.jl/stable/](https://evizero.github.io/Augmentor.jl/stable/)
2. `rm -rf LICENSE assets background generated gettingstarted images indices interface operations search search_index.js`

**Comment by johnnychen94** [comment]
LGTM

That documentation was written back to when Documenter.jl didn't exist yet. I believe my Documenter setup (#52) has fully covered every information, with some unsolved opened as issues (#67, #70, #54) so I believe it's safe to remove all those.
